name: Setup environment
description: Set up Java environment
runs:
  using: composite
  steps:
    - name: Validate Gradle
      uses: gradle/wrapper-validation-action@v1
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17
    - name: Making sure gradlew is executable
      shell: bash
      run: chmod +x ./gradlew
    - name: Install zsh
      shell: bash
      run: sudo apt-get update; sudo apt-get install zsh